# Internal service — Pod-to-Pod communication within the cluster.
# DNS: {{ include "legacy-app.fullname" . }}-clusterip.<namespace>.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.clusterIP.name }}
  labels:
    {{- include "legacy-app.labels" . | nindent 4 }}
    service-type: internal
spec:
  type: ClusterIP
  selector:
    {{- include "legacy-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.clusterIP.port }}
      targetPort: {{ .Values.service.clusterIP.targetPort }}
